aquastore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aquastore_app.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

aquastore_app/urls.py
from django.urls import path

from . import views

app_name = 'aquastore_app'

urlpatterns = [
    path(r'', views.lista_aguas, name='lista_aguas'),
    path(r'cat/<slug:slug_da_categoria>/', views.lista_aguas, name='lista_aguas_por_categoria'),
    path(r'produto/(<int:id>)', views.exibe_agua, name='exibe_agua'),
    path(r'sobre.html', views.sobre, name='sobre'),
    path(r'cadastro.html', views.novo, name='cadastro'),
    path(r'admin.html', views.admin, name='admin'),
    path(r'<int:id>/update', views.atualiza, name='atualiza'),
    path(r'<int:id>/delete', views.deleta, name='deleta'),
    path(r'register.html', views.register, name='register'),
    path(r'logout', views.logout_user, name='logout_user'),
]

carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho'

urlpatterns = [
    path('exibe_produtos_e_carrinho/', views.exibe_produtos_e_carrinho, name='exibe_produtos_e_carrinho'),
    path('exibe_produtos/', views.exibe_produtos, name='exibe_produtos'),
    path('exibe_carrinho/', views.exibe_carrinho, name='exibe_carrinho'),
    path('adicionar_ao_carrinho/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remove_produto_carrinho/', views.remove_produto_carrinho, name='remove_produto_carrinho'),
    path('atualiza_qtd_carrinho/', views.atualiza_qtd_carrinho, name='atualiza_qtd_carrinho'),
    path('adicionar/(<int:id>)', views.adicionar_produto, name='adicionar_produto'),

]

produto/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.lista_aguas, name='lista_aguas'),
    path('<slug:slug_da_categoria>/', views.lista_aguas, name='lista_aguas_por_categoria'),
    path('<int:id>/<slug:slug_da_agua>/', views.exibe_agua, name='exibe_agua'),
    path('sobre.html', views.sobre, name='sobre'),
]




# ####################################################################################################################
# Path converters¶
# The following path converters are available by default:
#
# str - Matches any non-empty string, excluding the path separator, '/'. This is the default if a converter isn’t included in the expression.
# int - Matches zero or any positive integer. Returns an int.
# slug - Matches any slug string consisting of ASCII letters or numbers, plus the hyphen and underscore characters. For example, building-your-1st-django-site.
# uuid - Matches a formatted UUID. To prevent multiple URLs from mapping to the same page, dashes must be included and letters must be lowercase. For example, 075194d3-6885-417e-a8a8-6c931e272f00. Returns a UUID instance.
# path - Matches any non-empty string, including the path separator, '/'. This allows you to match against a complete URL path rather than just a segment of a URL path as with str.
# ####################################################################################################################

# ####################################################################################################################
# Registering custom path converters
# For more complex matching requirements, you can define your own path converters.
#
# A converter is a class that includes the following:
#
# A regex class attribute, as a string.
# A to_python(self, value) method, which handles converting the matched string into the type that should be passed to the view function. It should raise ValueError if it can’t convert the given value.
# A to_url(self, value) method, which handles converting the Python type into a string to be used in the URL.
# For example:
#
# class FourDigitYearConverter:
#     regex = '[0-9]{4}'
#
#     def to_python(self, value):
#         return int(value)
#
#     def to_url(self, value):
#         return '%04d' % value
# ####################################################################################################################

# ####################################################################################################################
# Register custom converter classes in your URLconf using register_converter():
#
# from django.urls import register_converter, path
#
# from . import converters, views
#
# register_converter(converters.FourDigitYearConverter, 'yyyy')
#
# urlpatterns = [
#     path('articles/2003/', views.special_case_2003),
#     path('articles/<yyyy:year>/', views.year_archive),
#     ...
# ]
# ####################################################################################################################

# ####################################################################################################################
# Using regular expressions¶
# If the paths and converters syntax isn’t sufficient for defining your URL patterns, you can also use regular expressions. To do so, use re_path() instead of path().
#
# In Python regular expressions, the syntax for named regular expression groups is (?P<name>pattern), where name is the name of the group and pattern is some pattern to match.
#
# Here’s the example URLconf from earlier, rewritten using regular expressions:
#
# from django.urls import path, re_path
#
# from . import views
#
# urlpatterns = [
#     path('articles/2003/', views.special_case_2003),
#     re_path(r'^articles/(?P<year>[0-9]{4})/$', views.year_archive),
#     re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
#     re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[\w-]+)/$', views.article_detail),
# ]
# ####################################################################################################################

aquastore_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class CategoriaAguas(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        db_table = 'categoria_aguas'

    def get_absolute_path(self):
        return reverse('aquastore_app:lista_aguas_por_categoria', args=[self.slug])

    def __str__(self):
        return self.nome


class Agua(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    categoria = models.ForeignKey(CategoriaAguas, related_name='aguas', on_delete=models.DO_NOTHING)
    imagem = models.CharField(max_length=200)
    descricao = models.TextField(blank=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    estoque = models.PositiveIntegerField()
    disponivel = models.BooleanField(default=True)

    class Meta:
        db_table = 'agua'

    def get_absolute_path(self):
        return reverse('aquastore_app:exibe_agua', args=[self.id])

    def __str__(self):
        return self.nome

    def atualiza(self):
        return reverse('aquastore_app:atualiza',args=[self.id])

    def deleta(self):
        return reverse('aquastore_app:deleta',args=[self.id])

aquastore_app/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelForm
from aquastore_app.models import Agua, CategoriaAguas


class BuscaAguasForm(forms.Form):
    class Meta:
        fields = ('busca_por')

    busca_por = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control shadow-sm', 'maxlength': '120', 'placeholder': 'Busque por algum produto específico '}),
        required=False)


class AguaForm(ModelForm):
    class Meta:
        model = Agua
        fields = ['nome', 'categoria', 'imagem', 'descricao', 'preco', 'estoque', 'disponivel']

    nome = forms.CharField(
        error_messages={'required': 'Campo obrigatório.',
                        'unique': 'Produto duplicado.'},
        widget=forms.TextInput(
            attrs={
                'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    categoria = forms.ModelChoiceField(
        error_messages={'required': 'Campo obrigatório.', },
        queryset=CategoriaAguas.objects.all().order_by('nome'),
        empty_label='--- Selecione uma categoria ---',
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'}),
        required=True)

    imagem = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    descricao = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=False)

    preco = forms.DecimalField(
        localize=True,
        error_messages={'required': 'Campo obrigatório.', },
        validators=[RegexValidator(regex='^[0-9]{1,7}(,[0-9]{2})?$', message="Informe o valor no formato 9999999,99.")],
        widget=forms.NumberInput(attrs={'class': 'form-control form-control-sm',
                                      'maxlength': '10',
                                      'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57)'
                                                    ' || event.charCode == 44'}),
        required=True)

    estoque = forms.IntegerField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    disponivel = forms.BooleanField()

aquastore_app/views.py
from django.db.models import Sum, F, FloatField
from django.http import QueryDict, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from .models import CategoriaAguas, Agua
from aquastore_app.forms import AguaForm, BuscaAguasForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,    login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime


def lista_aguas(request, slug_da_categoria=None):
    categoria = None
    categorias = CategoriaAguas.objects.all().order_by("nome")
    aguas = Agua.objects.filter(disponivel=True).order_by("id")

    if slug_da_categoria:
        categoria = get_object_or_404(CategoriaAguas, slug=slug_da_categoria)
        aguas = aguas.filter(categoria=categoria).order_by("nome")

    busca = request.GET.get('busca_por')
    form = BuscaAguasForm()

    if busca:
        aguas = aguas.filter(nome__icontains=busca)

    qtdElem = aguas.count()

    paginator = Paginator(aguas, 12)
    page = request.GET.get('page')
    try:
        aguas_lista = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        aguas_lista = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        aguas_lista = paginator.page(paginator.num_pages)

    return render(request, 'aquastore_app/lista.html', {'categorias': categorias,
                                                        'page': page,
                                                        'qtdElem': qtdElem,
                                                        'busca': busca,
                                                        'aguas_lista': aguas_lista,
                                                        'categoria': categoria,
                                                        'form': form})


def exibe_agua(request, id):
    agua = Agua.objects.get(id=id)
    return render(request, 'aquastore_app/exibe.html', {'agua': agua})


def sobre(request):
    return render(request, 'aquastore_app/sobre.html')


def cadastro(request):
    return render(request, 'aquastore_app/cadastro.html')


@login_required
def admin(request):
    return render(request, 'aquastore_app/admin.html')

# @login_required(login_url='/autenticacao')
def novo(request):
    form = AguaForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'aquastore_app/cadastro.html', {'form': form})


def atualiza(request, id):
    agua = Agua.objects.get(id=id)
    form = AguaForm(request.POST or None, instance=agua)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'aquastore_app/cadastro.html', {'form': form})


def deleta(request, id):
    agua = Agua.objects.get(id=id)
    agua.delete()
    return redirect('/')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('/')

###############################################################################################

aquastore_app/templates/aquastore_app/admin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "base/header.html" %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner shadow">
         <div class="carousel-item active">
            <img class="carousel-inner-page d-block w-100" src="{% static 'media/wave.jpg' %}" alt="First slide">
            <div class="carousel-caption carousel-inner-text d-none d-md-block">
               <h1 style="text-shadow: 1px 1px 2px grey;">Área do administrador</h1>
            </div>
         </div>
      </div>
    </div>
</head>

{% block estilo %}
    <style>
        a {
            color: #337ab7;
        }
    </style>
{% endblock %}

{% block conteudo %}
    <body class="bg-white">
    <div class="container bg-white" style="margin-top: 90px;">
        <div class="row">
            <div class="col-lg-12">
                <div class="card-home mb-3 shadow-sm" style="align-items: center">
                    <h3 class="mt-5 text-center">Cadastro de produto</h3>

                    <p class="text-center">Clique aqui para inserir um novo produto</p>
                    <a href="{% url 'aquastore_app:cadastro' %}" class="btn btn-primary mb-5">Novo produto</a>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    {% include "base/footer.html" %}
    </body>
    <script src="{% static 'aquastore_app/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'aquastore_app/js/popper.js' %}"></script>
    <script src="{% static 'aquastore_app/js/bootstrap.js' %}"></script>
    <script src="{% static 'aquastore_app/js/script.js' %}"></script>

{% endblock %}

aquastore_app/templates/aquastore_app/cadastro.html
{% load static %}
{% load bootstrap %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "base/header.html" %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner shadow">
         <div class="carousel-item active">
            <img class="carousel-inner-page d-block w-100" src="{% static 'media/refract.jpg' %}" alt="First slide">
            <div class="carousel-caption carousel-inner-text d-none d-md-block">
               <h1 style="text-shadow: 1px 1px 2px grey;">Cadastro de produto</h1>
            </div>
         </div>
      </div>

   </div>
    <br>
</head>

{% block content %}
<div class="container mb-4" style="margin-top: 50px;">
    <form method="POST" novalidate>

            {% csrf_token %}

        <fieldset>
            <p>Nome: {{ form.nome }}</p>
            {% for error in form.nome.errors %}
                <p class="help" style="color: red;">{{ error }}</p>
            {% endfor %}
            <p>Categoria: {{ form.categoria }}</p>
            {% for error in form.categoria.errors %}
                <p class="help" style="color: red;">{{ error }}</p>
            {% endfor %}
            <p>Preço: {{ form.preco }}</p>
            {% for error in form.preco.errors %}
                <p class="help" style="color: red;">{{ error }}</p>
            {% endfor %}
            <p>Estoque: {{ form.estoque }}</p>
            {% for error in form.estoque.errors %}
                <p class="help" style="color: red;">{{ error }}</p>
            {% endfor %}
            <p>Disponivel: {{ form.disponivel }}</p>

            <p>Imagem: {{ form.imagem }}</p>
            {% for error in form.imagem.errors %}
                <p class="help" style="color: red;">{{ error }}</p>
            {% endfor %}
            <p>Descrição: {{ form.descricao }}</p>

        </fieldset>

            <button class="btn btn-primary" type="submit">Salvar</button>

    </form>
</div>

{% include "base/footer.html" %}

{% endblock %}

<script src="{% static 'aquastore_app/js/jquery-3.3.1.js' %}"></script>
<script src="{% static 'aquastore_app/js/popper.js' %}"></script>
<script src="{% static 'aquastore_app/js/bootstrap.js' %}"></script>
<script src="{% static 'aquastore_app/js/script.js' %}"></script>

aquastore_app/templates/aquastore_app/exibe.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

</head>


{% block estilo %}
    <style>
        a {
            color: #337ab7;
        }
    </style>
{% endblock %}

{% block conteudo %}
    <body class="bg-white">
    <div class="container bg-white p-1 mb-5 " style="margin-top: 90px ;">
        <div class="row">
            <div class="col-lg-6 mb-3 mb-md-0">
                <!-- style="min-height: 150px; min-width: 150px;" -->
                <img class="img-fluid rounded shadow-sm water-view"
                     src="{% static 'aguas/' %}{{ agua.imagem }}">
            </div>
            <div class="col-lg-6">
                <h1>{{ agua.nome }}</h1>
                <h4><a href="{{ agua.categoria.get_absolute_path }}">{{ agua.categoria }}</a></h4>
                <h1>R$ {{ agua.preco }}</h1>
                <p>{{ agua.descricao }}</p>

                 <a href="{% url 'carrinho:adicionar_produto' agua.id %}">
                     <button class="btn btn-primary shadow-sm"
                             data-toggle="modal" data-target="#confirmationModal" id="btn-compra">
                         <i class="fas fa-shopping-cart"></i>
                    Adicionar ao Carrinho</button></a>
                    <br><br>
                {% if user.is_authenticated %}
                <a href="{{ agua.atualiza }}"><button class="btn-sm shadow-sm btn btn-primary mb-5" style="align-self: center">
                    <i class="fas fa-edit"></i> Atualizar</button></a>
                <button data-toggle="modal" data-target="#deleteModal" class="btn shadow-sm btn-sm btn-danger mb-5" style="align-self: center">
                    <i class="fas fa-times-circle"></i> Excluir</button>
                {% endif %}

            </div>
        </div>

        <div class="col-lg-12">

            <h3 style="text-align:center">{% if categoria %}{{ categoria.nome }}{% endif %}</h3>
            <div class="row mb-6 p-3">
                {% for agua in aguas_lista %}
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                    <a href="{{ agua.get_absolute_path }}">
                        <div class="card-home mb-3 shadow-sm" style="align-items: center">

                                    <!-- style="max-width: 90%;" -->
                                <img class="img-fluid rounded water-product"
                                         src="{% static 'aguas/' %}{{ agua.imagem }}">
                            <h5 class="mt-3 card-title text-center">

                                    {{ agua.nome }}

                            </h5>
                            R$ {{ agua.preco }}
                            <br>

                        </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ótima escolha!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Produto adicionado com sucesso ao carrinho!
          </div>

        </div>
      </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Deseja realmente excluir o produto selecionado?
          </div>
            <div class="modal-footer">
                <a href="{{ agua.deleta }}">
              <button type="button" class="btn btn-danger">Sim</button>
                    </a>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
             </div>

        </div>
      </div>
    </div>
    </body>
    <script src="{% static 'aquastore_app/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'aquastore_app/js/popper.js' %}"></script>
    <script src="{% static 'aquastore_app/js/bootstrap.js' %}"></script>
    <script src="{% static 'aquastore_app/js/script.js' %}"></script>

{% endblock %}
{% block domready %}
    $("#produtos").on("click", "button.adicionar", function () {
        window.alert("AAAAAAA")
        let form = $(this).parent().prev().children('form')
        let input = $(form).children('input.quantidade')
        if (input.val() <= 0) {
            $(input).focus()
            return
        }
        let tr = $(form).parent().parent()
        let ind = $(tr).index()
        let valor_id = ids_dos_produtos[ind]
        $(form).append("<input type='hidden' name='produto_id' value='" + valor_id + "'>")
        let url = $(form).attr('action')
        let formData = $(form).serializeArray()
        $.post(url, formData, function (resposta) {
            // console.log(resposta)
            $("#carrinho").html(resposta)
            ids_dos_produtos_no_carrinho = recuperaIds(resposta)
            // console.log(ids_dos_produtos_no_carrinho)
        })
    })
{% endblock %}
{% include "base/footer.html" %}

aquastore_app/templates/aquastore_app/lista.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Produtos
{% endblock %}

{% block estilo %}
    <style>
        .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
            color: #fff;
            background-color: #337ab7;
        }

        a.nav-link:hover {
            background-color: #eeeeee;
        }

        a {
            color: #337ab7;
        }
    </style>
{% endblock %}

{% block conteudo %}
    {% include "base/carousel.html" %}

    <div class="container bg-white p-3 mb-5">
    <form action="{% url 'aquastore_app:lista_aguas' %}" method ='GET' class="mt-5">
      <div class='form-group row' style='margin-bottom: 10px; margin-left: 30px'>
         <div class='col-lg-10'>
            {{ form.busca_por }}
         </div>
         <div class="col-lg-2">
            <button type='submit' class='shadow-sm btn btn-primary'>
                <i class="fas fa-search"></i>
               Buscar
            </button>
         </div>
      </div>
    </form>
    <div class="row" >

        <div class="col-lg-12">
        <h3 style="text-align:center" class="mb-3 mt-2">{% if busca %} Busca por '{{ busca }}': {{ qtdElem }} resultado(s){% endif %}</h3>
            <h3 style="text-align:center" class="mb-3 mt-2">{% if not categoria %}{% else %}Categoria: {{ categoria.nome }}{% endif %}</h3>
            <div class="row mb-6 p-3">
                {% for agua in aguas_lista %}
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                    <a href="{{ agua.get_absolute_path }}">
                        <div class="card-home mb-3 shadow-sm" style="align-items: center">

                                    <!-- style="max-width: 90%;" -->
                                <img class="img-fluid rounded water-product"
                                         src="{% static 'aguas/' %}{{ agua.imagem }}">
                            <h5 class="mt-3 card-title text-center text-primary">

                                    {{ agua.nome }}

                            </h5>
                            <b class="text-success">R$ {{ agua.preco }}</b>
                            <br>
                            <br>
                        </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
     <div class="pagination justify-content-center">

        {% if aguas_lista.has_other_pages %}
            <nav aria-label="Navegação"></nav>
                <ul class="pagination justify-content-center">
                    {% if aguas_lista.has_previous %}
                    <li><a href="?page={{ aguas_lista.previous_page_number }}" class="page-link">&laquo; Página anterior </a></li>
                    {% endif %}
                    {% for i in aguas_lista.paginator.page_range %}
                         {% if aguas_lista.number == i %}
                            <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
                         {% else %}
                            <li class='page-item'><a class='page-link' href='?page={{ i }}'>{{ i }}</a></li>
                         {% endif %}
                    {% endfor %}
                    {% if aguas_lista.has_next %}
                    <li><a href="?page={{ aguas_lista.next_page_number }}" class="page-link"> Próxima página &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

    </div>
    </div>

    {% endblock %}

aquastore_app/templates/aquastore_app/sobre.html
{% load static %}


<!DOCTYPE html>
<head>
    {% include "base/header.html" %}
    {% include "base/bgimage.html" %}
    <br>
</head>
<body class="bg-white">
   <div class="container bg-white p-3 mb-5 text-justify">
       <img src="{% static 'media/water-icon.png' %}" class="rounded mx-auto d-block">
      <h5 style="margin-top: 10px; text-align: justify">A Aqua Store é uma loja virtual de águas, fundada em 2019, pelo
         sommelier
         de águas Lucas de Castro Lopes. <br>

         Nosso objetivo é levar para todos a saúde e a refrescância que apenas um bom copo d'água pode trazer. <br>
         Boas compras!
      </h5>

      <h6 style="margin-top: 30px; margin-bottom:30px; text-align: justify">Em 2017, o então estudante de Ciência da Computação Lucas de
            Castro Lopes
            foi apresentado ao mundo da degustação de águas gourmet. Inicialmente ele achou isso uma perda de tempo,
            pois "como que
            águas poderiam ter gostos distintos? É tudo água!" <br>
            No entanto, o tempo se mostrou aliado de Lucas, e pouco tempo depois, já dentro do universo das águas, teve a
            ideia de
            criar um site para apresentar as diferentes águas às pessoas do Brasil e do mundo. Assim, o embrião da Aqua
            Store
            estava nascendo.<br>
            Logo, a Aqua Store passou a ter como objetivo vender água em geral, saindo apenas do nicho das águas
            gourmet.

      </h6>

      <h3 style="text-align: center">Degustação de águas gourmet</h3>
      <br>
      <div class="embed-responsive embed-responsive-21by9">
         <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/juf4EVFTNNE" allowfullscreen></iframe>
      </div>
      <div style="margin-top: 30px" class="jumbotron text-center mb-4 bg-white">
         <blockquote class="blockquote">
            <p>Hidrate-se!
            </p>
            <div class="blockquote-footer">
               Lucas de Castro Lopes
            </div>
         </blockquote>

      </div>
   </div>
   <br>
   {% include "base/footer.html" %}

   <script src="{% static 'aquastore_app/js/jquery-3.3.1.js' %}"></script>
   <script src="{% static 'aquastore_app/js/popper.js' %}"></script>
   <script src="{% static 'aquastore_app/js/bootstrap.js' %}"></script>
   <script src="{% static 'aquastore_app/js/script.js' %}"></script>
</body>

</html>