aquastore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aquastore_app.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

aquastore_app/urls.py
from django.urls import path

from . import views

app_name = 'aquastore_app'

urlpatterns = [
    path(r'', views.lista_aguas, name='lista_aguas'),
    path(r'cat/<slug:slug_da_categoria>/', views.lista_aguas, name='lista_aguas_por_categoria'),
    path(r'produto/(<int:id>)', views.exibe_agua, name='exibe_agua'),
    path(r'sobre.html', views.sobre, name='sobre'),
    path(r'cadastro.html', views.novo, name='cadastro'),
    path(r'admin.html', views.admin, name='admin'),
    path(r'<int:id>/update', views.atualiza, name='atualiza'),
    path(r'<int:id>/delete', views.deleta, name='deleta'),
    path(r'register.html', views.register, name='register'),
    path(r'logout', views.logout_user, name='logout_user'),
]

carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho'

urlpatterns = [
    path('exibe_produtos_e_carrinho/', views.exibe_produtos_e_carrinho, name='exibe_produtos_e_carrinho'),
    path('exibe_produtos/', views.exibe_produtos, name='exibe_produtos'),
    path('exibe_carrinho/', views.exibe_carrinho, name='exibe_carrinho'),
    path('adicionar_ao_carrinho/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remove_produto_carrinho/', views.remove_produto_carrinho, name='remove_produto_carrinho'),
    path('atualiza_qtd_carrinho/', views.atualiza_qtd_carrinho, name='atualiza_qtd_carrinho'),
    path('adicionar/(<int:id>)', views.adicionar_produto, name='adicionar_produto'),

]

produto/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.lista_aguas, name='lista_aguas'),
    path('<slug:slug_da_categoria>/', views.lista_aguas, name='lista_aguas_por_categoria'),
    path('<int:id>/<slug:slug_da_agua>/', views.exibe_agua, name='exibe_agua'),
    path('sobre.html', views.sobre, name='sobre'),
]




# ####################################################################################################################
# Path converters¶
# The following path converters are available by default:
#
# str - Matches any non-empty string, excluding the path separator, '/'. This is the default if a converter isn’t included in the expression.
# int - Matches zero or any positive integer. Returns an int.
# slug - Matches any slug string consisting of ASCII letters or numbers, plus the hyphen and underscore characters. For example, building-your-1st-django-site.
# uuid - Matches a formatted UUID. To prevent multiple URLs from mapping to the same page, dashes must be included and letters must be lowercase. For example, 075194d3-6885-417e-a8a8-6c931e272f00. Returns a UUID instance.
# path - Matches any non-empty string, including the path separator, '/'. This allows you to match against a complete URL path rather than just a segment of a URL path as with str.
# ####################################################################################################################

# ####################################################################################################################
# Registering custom path converters
# For more complex matching requirements, you can define your own path converters.
#
# A converter is a class that includes the following:
#
# A regex class attribute, as a string.
# A to_python(self, value) method, which handles converting the matched string into the type that should be passed to the view function. It should raise ValueError if it can’t convert the given value.
# A to_url(self, value) method, which handles converting the Python type into a string to be used in the URL.
# For example:
#
# class FourDigitYearConverter:
#     regex = '[0-9]{4}'
#
#     def to_python(self, value):
#         return int(value)
#
#     def to_url(self, value):
#         return '%04d' % value
# ####################################################################################################################

# ####################################################################################################################
# Register custom converter classes in your URLconf using register_converter():
#
# from django.urls import register_converter, path
#
# from . import converters, views
#
# register_converter(converters.FourDigitYearConverter, 'yyyy')
#
# urlpatterns = [
#     path('articles/2003/', views.special_case_2003),
#     path('articles/<yyyy:year>/', views.year_archive),
#     ...
# ]
# ####################################################################################################################

# ####################################################################################################################
# Using regular expressions¶
# If the paths and converters syntax isn’t sufficient for defining your URL patterns, you can also use regular expressions. To do so, use re_path() instead of path().
#
# In Python regular expressions, the syntax for named regular expression groups is (?P<name>pattern), where name is the name of the group and pattern is some pattern to match.
#
# Here’s the example URLconf from earlier, rewritten using regular expressions:
#
# from django.urls import path, re_path
#
# from . import views
#
# urlpatterns = [
#     path('articles/2003/', views.special_case_2003),
#     re_path(r'^articles/(?P<year>[0-9]{4})/$', views.year_archive),
#     re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
#     re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[\w-]+)/$', views.article_detail),
# ]
# ####################################################################################################################

carrinho/models.py
from django.db import models

# Create your models here.

carrinho/forms.py
from django import forms

class RemoveProdutoDoCarrinhoForm(forms.Form):
    class Meta:
        fields = ('produto_id')

    produto_id = forms.CharField(widget=forms.HiddenInput())

class QuantidadeForm(forms.Form):
    class Meta:
        fields = ('quantidade', 'produto_id')

    # <input type="hidden" name="produto_id" id="id_produto_id" value="xxx">
    produto_id = forms.CharField(widget=forms.HiddenInput())

    quantidade = forms.IntegerField(
        min_value=1,
        max_value=1000,
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm quantidade',
                                      'maxlength': '20',
                                      'onkeypress': 'return event.charCode >= 48 && event.charCode <= 57'}),
        required=True)

carrinho/views.py
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from .carrinho import Carrinho
from .forms import QuantidadeForm, RemoveProdutoDoCarrinhoForm
from aquastore_app.models import Agua
from aquastore_app.views import lista_aguas

@login_required(login_url='/autenticacao/login')
def exibe_produtos_e_carrinho(request):
    return render(request, 'carrinho/vendas.html')

@login_required(login_url='/autenticacao/login')
def exibe_produtos(request):
    produtos = Agua.objects.all()
    lista_de_forms = []
    for p in produtos:
        lista_de_forms.append(QuantidadeForm(initial={'quantidade': 0}))

    return render(request, 'carrinho/produtos_a_venda.html',  {
        'listas': zip(produtos, lista_de_forms)
    })

@login_required(login_url='/autenticacao/login')
def exibe_carrinho(request):
    carrinho = Carrinho(request)

    lista_de_produtos_no_carrinho = carrinho.get_produtos()

    valoresInd = []
    for item in lista_de_produtos_no_carrinho:
        valoresInd.append(int(item['quantidade']) * Decimal(item['preco']))

    produtos_no_carrinho = []
    lista_de_forms = []
    valor_do_carrinho = 0
    for item in lista_de_produtos_no_carrinho:
        produtos_no_carrinho.append(item['produto'])
        lista_de_forms.append(QuantidadeForm(initial={'quantidade': item['quantidade']}))
        valor_do_carrinho = valor_do_carrinho + int(item['quantidade']) * Decimal(item['preco'])

    return render(request, 'carrinho/produtos_no_carrinho.html',  {
        'listas': zip(produtos_no_carrinho, lista_de_forms, valoresInd),
        'valor_do_carrinho': valor_do_carrinho,
    })

@login_required(login_url='/autenticacao/login')
def adicionar_ao_carrinho(request):
    form = QuantidadeForm(request.POST)
    if form.is_valid():
        quantidade = form.cleaned_data['quantidade']
        produto_id = form.cleaned_data['produto_id']

        carrinho = Carrinho(request)
        carrinho.adicionar(produto_id, quantidade)

        return exibe_carrinho(request)
    else:
        print(form.errors)
        raise ValueError('Ocorreu um erro inesperado ao adicionar um produto ao carrinho.')


@login_required(login_url='/autenticacao/login')
def adicionar_produto(request, id):
    produto_id = id

    carrinho = Carrinho(request)
    carrinho.adicionar(produto_id, 1)

    return lista_aguas(request)


@login_required(login_url='/autenticacao/login')
def remove_produto_carrinho(request):
    form = RemoveProdutoDoCarrinhoForm(request.POST)
    if form.is_valid():
        carrinho = Carrinho(request)
        carrinho.remover(form.cleaned_data['produto_id'])

        return exibe_carrinho(request)
    else:
        print(form.errors)
        raise ValueError('Ocorreu um erro inesperado ao adicionar um produto ao carrinho.')

@login_required(login_url='/autenticacao/login')
def atualiza_qtd_carrinho(request):
    form = QuantidadeForm(request.POST)
    if form.is_valid():
        produto_id = form.cleaned_data['produto_id']
        quantidade = form.cleaned_data['quantidade']

        carrinho = Carrinho(request)
        carrinho.alterar(produto_id, quantidade)

        return exibe_carrinho(request)
    else:
        print(form.errors)
        raise ValueError('Ocorreu um erro inesperado ao adicionar um produto ao carrinho.')

carrinho/templates/carrinho/produtos_a_venda.html
{% load static %}

<div class="w3-content w3-display-container" style="margin-top: 100px ;">
    <div class="col-12">
        <h4 class="titulo mb-0">Lista de Produtos</h4>
        <hr class="mt-2 mb-4">
    </div>

    <div class="col-12">
        <div class="table-responsive">
            <table style="width:100%" class="table table-striped table-sm table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Número</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Preço</th>
                        <th class="text-center">Quantidade</th>
                        <th class="text-center">Remover</th>
                    </tr>
                </thead>
                <tbody id="tbody1">
                    {% for produto, form in listas %}
                        <tr>
                            <td width="10%" class="text-center id">
                                <a href="{% url 'produto:item' produto.id %}">
                                <img class="card-img-top" src="{% static 'produto/imagens/' %}{{ produto.imagem }}">
                                </a>
                                    {{ produto.id }}
                            </td>
                            <td width="35%">
                                <a href="{% url 'produto:item' produto.id %}">
                                {{ produto.nome }}
                                </a>
                            </td>
                            <td width="15%" class="text-center">
                                {{ produto.preco }}
                            </td>
                            <td width="15%" class="text-center">
                                <form class="mx-auto" style="width: 60px;" 
                                      action ="{% url 'carrinho:adicionar_ao_carrinho' %}"
                                      method ="POST" novalidate>
                                    {% csrf_token %}
                                    {{ form.quantidade }}
                                </form>
                            </td>
                            <td width="25%" class="text-center">
                                <button style="margin-top: 0px; margin-bottom: 0px; padding-top: 3px; padding-bottom: 3px;"
                                        type="button" class="btn btn-sm btn-primary adicionar">
                                    Adicionar ao Carrinho
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

carrinho/templates/carrinho/produtos_no_carrinho.html
{% load static %}

<div>
    <div class="w3-content w3-display-container" style="" >


        <div class="col-12">
            <div class="table-responsive">
                <table style="width:100%" class="table table-lg table-bordered">
                    <thead>
                    <tr>
                        <th class="text-center">Produto</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Preço</th>
                        <th class="text-center">Quantidade</th>
                        <th class="text-center">Total</th>
                        <th class="text-center">Remover</th>

                    </tr>
                    </thead>
                    <tbody id="tbody2">
                    {% for agua, form, valores_ind in listas %}
                        <tr>
                            <td width="10%" class="text-center id">
                                <a href="{% url 'aquastore_app:exibe_agua' agua.id %}">
                                    <img class="card-img-top" src="{% static 'aguas/' %}{{ agua.imagem }}">
                                </a>

                            </td>
                            <td width="35%">
                                {{ agua.nome }}
                            </td>
                            <td width="15%" class="text-center">
                                {{ agua.preco }}
                            </td>
                            <td width="15%" class="text-center">
                                <form class="mx-auto" style="width: 60px;" action ="{% url 'carrinho:atualiza_qtd_carrinho' %}"
                                      method ="POST" novalidate>
                                    {% csrf_token %}
                                    {{ form.quantidade }}
                                </form>
                            </td>
                                                        <td width="10%" class="text-center">
                                {{ valores_ind }}
                            </td>


                            <td width="10%" class="text-center">
                                <form style="margin-bottom: 0px;"
                                      action ="{% url 'carrinho:remove_produto_carrinho' %}"
                                      method ="post" novalidate>
                                    {% csrf_token %}
                                    <button style="margin-top: 0px; margin-bottom: 0px; padding-top: 3px; padding-bottom: 3px;"
                                            type="button" class="btn btn-sm btn-danger btn-remove">
                                        Remover
                                    </button>
                                </form>
                            </td>


                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="4" width="90%" class="text-left">
                            <strong style="margin-left: 10px;">Subtotal</strong>
                        </td>
                        <td width="10%" class="text-right pr-3">
                            <strong id="valor-do-estoque">{{ valor_do_carrinho }}</strong>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

carrinho/templates/carrinho/vendas.html
{% extends "base.html" %}

{% load filtros %}

{% load static %}



{% block conteudo %}
    <!--
    <br>
    <div id="produtos">

    </div>
        -->
    <head>
    {% include "base/header.html" %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner shadow">
         <div class="carousel-item active">
            <img class="carousel-inner-page d-block w-100" src="{% static 'media/drop2.jpg' %}" alt="First slide">
            <div class="carousel-caption carousel-inner-text d-none d-md-block">
               <h1 style="text-shadow: 1px 1px 2px grey;">Carrinho de compras</h1>
            </div>
         </div>
      </div>

   </div>
</head>
    <br>
    <div class="container">
        <div style="margin-top: 30px" id="carrinho">

        </div>
    </div>
    <br/>
    <br/>
    <br/>
{% endblock %}


{% block domready %}
    let ids_dos_produtos = []
    let ids_dos_produtos_no_carrinho = []

    $.get('{% url 'carrinho:exibe_produtos' %}', function(resposta) {
        $("#produtos").html(resposta)
    })
    .done(function() {
        let ids = $("#tbody1 td.id")
        $(ids).each(function() {
           var id = parseInt($(this).text());
           // console.log("venda - id = " + id)
           ids_dos_produtos.push(id)
        })
        // console.log(">>>> " + ids_dos_produtos)
    })

    $.get('{% url 'carrinho:exibe_carrinho' %}', function(resposta) {
        $("#carrinho").html(resposta)
    })
    .done(function() {
        let ids = $("#tbody2 td.id")
        $.each( ids, function( i, val ) {
           var id = parseInt($(val).text());
           // console.log("carrinho - id = " + id)
           ids_dos_produtos_no_carrinho.push(id)
        })
        // console.log(">>>>>>> " + ids_dos_produtos_no_carrinho)
    })

    $("#produtos").on("click", "button.adicionar", function () {
        let form = $(this).parent().prev().children('form')
        let input = $(form).children('input.quantidade')
        if (input.val() <= 0) {
           $(input).focus()
           return
        }
        let tr = $(form).parent().parent()
        let ind = $(tr).index()
        let valor_id = ids_dos_produtos[ind]
        $(form).append("<input type='hidden' name='produto_id' value='" + valor_id + "'>")
        let url = $(form).attr('action')
        let formData = $(form).serializeArray()
        $.post(url, formData, function (resposta) {
           // console.log(resposta)
           $("#carrinho").html(resposta)
           ids_dos_produtos_no_carrinho = recuperaIds(resposta)
           // console.log(ids_dos_produtos_no_carrinho)
        })
    })

    $("#carrinho").on("click", "button.btn-remove", function() {
        let form = $(this).parent();
        let tr = $(form).parent().parent();
        let ind = $(tr).index();
        let valor_id = ids_dos_produtos_no_carrinho[ind];
        let input = "<input type='hidden' name='produto_id' value='" + valor_id + "'>";
        $(form).append(input);
        let url = $(form).attr('action')
        let formData = $(form).serializeArray()
        $.post(url, formData, function(resposta) {
           $("#carrinho").html(resposta)
           ids_dos_produtos_no_carrinho = recuperaIds(resposta)
           // console.log(ids_dos_produtos_no_carrinho)
        })
    })

    $("#carrinho").on("blur", "input.quantidade", function() {
        let valor = $(this).val()
        if (valor < 1 || valor > 1000) {
           $(this).focus()
           return
        }
        let form = $(this).parent()
        let tr = $(form).parent().parent();
        let ind = $(tr).index();
        let valor_id = ids_dos_produtos_no_carrinho[ind];
        $(form).append("<input type='hidden' name='produto_id' value='" + valor_id + "'>")
        let url = $(form).attr('action')
        let formData = $(form).serializeArray()
        $.post(url, formData, function(resposta) {
           $("#carrinho").html(resposta)
           ids_dos_produtos_no_carrinho = recuperaIds(resposta)
           console.log(ids_dos_produtos_no_carrinho)
        })
    })

    function recuperaIds(resposta) {
        var ids = $(resposta).find("td.id")
        var ids_dos_produtos_no_carrinho = []
        $(ids).each(function() {
           let id = parseInt($(this).text());
           ids_dos_produtos_no_carrinho.push(id)
        })
        return ids_dos_produtos_no_carrinho
    }

{% endblock %}