aquastore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aquastore_app.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

aquastore_app/urls.py
from django.urls import path

from . import views

app_name = 'aquastore_app'

urlpatterns = [
    path(r'', views.lista_aguas, name='lista_aguas'),
    path(r'cat/<slug:slug_da_categoria>/', views.lista_aguas, name='lista_aguas_por_categoria'),
    path(r'produto/(<int:id>)', views.exibe_agua, name='exibe_agua'),
    path(r'sobre.html', views.sobre, name='sobre'),
    path(r'cadastro.html', views.novo, name='cadastro'),
    path(r'admin.html', views.admin, name='admin'),
    path(r'<int:id>/update', views.atualiza, name='atualiza'),
    path(r'<int:id>/delete', views.deleta, name='deleta'),
    path(r'register.html', views.register, name='register'),
    path(r'logout', views.logout_user, name='logout_user'),
]

autenticacao/urls.py
from django.urls import path

from autenticacao.views import login_user, submit_login, logout_user
app_name = 'autenticacao'

urlpatterns = [
    path('login', login_user, name='login_user'),
    path('submit', submit_login, name='submit_login'),
    path('logout', logout_user, name='logout_user'),
]

carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho'

urlpatterns = [
    path('exibe_produtos_e_carrinho/', views.exibe_produtos_e_carrinho, name='exibe_produtos_e_carrinho'),
    path('exibe_produtos/', views.exibe_produtos, name='exibe_produtos'),
    path('exibe_carrinho/', views.exibe_carrinho, name='exibe_carrinho'),
    path('adicionar_ao_carrinho/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remove_produto_carrinho/', views.remove_produto_carrinho, name='remove_produto_carrinho'),
    path('atualiza_qtd_carrinho/', views.atualiza_qtd_carrinho, name='atualiza_qtd_carrinho'),
    path('adicionar/(<int:id>)', views.adicionar_produto, name='adicionar_produto'),

]

produto/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.lista_aguas, name='lista_aguas'),
    path('<slug:slug_da_categoria>/', views.lista_aguas, name='lista_aguas_por_categoria'),
    path('<int:id>/<slug:slug_da_agua>/', views.exibe_agua, name='exibe_agua'),
    path('sobre.html', views.sobre, name='sobre'),
]




# ####################################################################################################################
# Path converters¶
# The following path converters are available by default:
#
# str - Matches any non-empty string, excluding the path separator, '/'. This is the default if a converter isn’t included in the expression.
# int - Matches zero or any positive integer. Returns an int.
# slug - Matches any slug string consisting of ASCII letters or numbers, plus the hyphen and underscore characters. For example, building-your-1st-django-site.
# uuid - Matches a formatted UUID. To prevent multiple URLs from mapping to the same page, dashes must be included and letters must be lowercase. For example, 075194d3-6885-417e-a8a8-6c931e272f00. Returns a UUID instance.
# path - Matches any non-empty string, including the path separator, '/'. This allows you to match against a complete URL path rather than just a segment of a URL path as with str.
# ####################################################################################################################

# ####################################################################################################################
# Registering custom path converters
# For more complex matching requirements, you can define your own path converters.
#
# A converter is a class that includes the following:
#
# A regex class attribute, as a string.
# A to_python(self, value) method, which handles converting the matched string into the type that should be passed to the view function. It should raise ValueError if it can’t convert the given value.
# A to_url(self, value) method, which handles converting the Python type into a string to be used in the URL.
# For example:
#
# class FourDigitYearConverter:
#     regex = '[0-9]{4}'
#
#     def to_python(self, value):
#         return int(value)
#
#     def to_url(self, value):
#         return '%04d' % value
# ####################################################################################################################

# ####################################################################################################################
# Register custom converter classes in your URLconf using register_converter():
#
# from django.urls import register_converter, path
#
# from . import converters, views
#
# register_converter(converters.FourDigitYearConverter, 'yyyy')
#
# urlpatterns = [
#     path('articles/2003/', views.special_case_2003),
#     path('articles/<yyyy:year>/', views.year_archive),
#     ...
# ]
# ####################################################################################################################

# ####################################################################################################################
# Using regular expressions¶
# If the paths and converters syntax isn’t sufficient for defining your URL patterns, you can also use regular expressions. To do so, use re_path() instead of path().
#
# In Python regular expressions, the syntax for named regular expression groups is (?P<name>pattern), where name is the name of the group and pattern is some pattern to match.
#
# Here’s the example URLconf from earlier, rewritten using regular expressions:
#
# from django.urls import path, re_path
#
# from . import views
#
# urlpatterns = [
#     path('articles/2003/', views.special_case_2003),
#     re_path(r'^articles/(?P<year>[0-9]{4})/$', views.year_archive),
#     re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
#     re_path(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<slug>[\w-]+)/$', views.article_detail),
# ]
# ####################################################################################################################

templates/base/bgimage.html
{% load static %}

{% block bgimage %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner shadow">
         <div class="carousel-item active">
            <img class="carousel-inner-page d-block w-100" src="{% static 'media/cup.jpg' %}" alt="First slide">
             <div class="carousel-caption carousel-inner-text d-none d-md-block">
               <h1 style="text-shadow: 1px 1px 2px grey;">Sobre nós</h1>
            </div>
         </div>

      </div>

   </div>

{% endblock %}

templates/base/carousel.html
{% load static %}

{% block carousel %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner shadow">
            <div class="carousel-item active">
                <img class="carousel-home d-block w-100" src="{% static 'media/water2.jpg' %}"
                     alt="First slide">
                <div class="carousel-caption d-none d-sm-block">
                    <h1 style="text-shadow: 1px 1px 2px grey;">Água é vida.</h1>
                    <p style="text-shadow: 1px 1px 2px grey;">Confira nosso catálogo de águas</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="carousel-home d-block w-100" src="{% static 'media/wave2.jpg' %}"
                     alt="Second slide">
                <div class="carousel-caption d-none d-sm-block">
                    <h1 style="text-shadow: 1px 1px 2px grey;">Águas gourmet pelo melhor preço.</h1>
                    <p style="text-shadow: 1px 1px 2px grey;">Você só encontra na Aqua Store</p>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/base/footer.html
{% load static %}
<footer class="footer">
   <div class="container">
      <div class="text-center">
          <p>© 2019. Aqua Store® é uma marca de Lucas de Castro Lopes.
              {% if user.is_authenticated %}
                        Usuário logado: {{ user.username }} |
                  <a href="{% url 'aquastore_app:admin' %}">Área do administrador </a> |
                  <a href="{% url 'autenticacao:logout_user' %}">Fazer logout</a>
                    {% else %}
                     <a href="{% url 'autenticacao:login_user' %}">Faça seu login</a> |
                     <a href="{% url 'aquastore_app:register' %}"> Crie sua conta</a>
                    {% endif %}
              </p>
      </div>
   </div>
</footer>

templates/base/header.html
{% load static %}
    <meta charset="UTF-8">
    <title>Aqua Store</title>
<header>
    <nav class="navbar navbar-light bg-white navbar-expand-lg fixed-top border-bottom shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'media/water-icon.png' %}" style="width: 105px;"
                     alt="Aqua Store">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#menu" aria-controls="menu"
                    aria-expanded="false" aria-label="Botão de navegação">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menu">

                <div class="navbar-nav mr-auto">
                    <a class="nav-link nav-item" href="/cat/gourmet">
                        <i class="fas fa-glass-cheers"></i> gourmet</a>
                    <a class="nav-link nav-item" href="/cat/tradicionais">
                        <i class="fas fa-wine-bottle"></i> tradicionais</a>
                    <a class="nav-link nav-item" href="/cat/outros">
                        <i class="fas fa-tools"></i> outros</a>
                </div>

                <div class="navbar-nav ml-auto">
                    <a class="nav-link nav-item" href="{% url 'carrinho:exibe_produtos_e_carrinho' %}">
                        <i class="fas fa-shopping-cart"></i> carrinho</a>
                    <a class="nav-link nav-item" href="{% url 'aquastore_app:sobre' %}">
                        <i class="fas fa-info-circle"></i> sobre nós</a>
                </div>



            </div>
        </div>
    </nav>

</header>

<link href="{% static 'aquastore_app/css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'aquastore_app/css/all.css' %}" rel="stylesheet">
<link href="{% static 'aquastore_app/css/styles.css' %}" rel="stylesheet">